--ELIMINAR RESTRICCIÒN (CONTRAINT) UNIQUE DE LAS TABLAS
---DE PAIS (Nombre)
ALTER TABLE PAIS 
DROP CONSTRAINT unq_PAIS_nombre;

---DE TIPO_MEDALLA (Medalla)
ALTER TABLE TIPO_MEDALLA 
DROP CONSTRAINT unq_TIPO_MEDALLA_medalla;


---DE DEPARTAMENTO (Nombre)
ALTER TABLE DEPARTAMENTO 
DROP CONSTRAINT unq_DEPARTAMENTO_nombre;


