--A) CREAR TABLA
--TABLA 17-
CREATE TABLE SEDE
(
    codigo INTEGER NOT NULL CONSTRAINT pk_SEDE PRIMARY KEY,
    sede VARCHAR(50) NOT NULL
);


--B) CAMBIAR TIPO DE DATO COLUMNA ubicacion (varchar) A entero
ALTER TABLE EVENTO 
ALTER COLUMN ubicacion 
SET DATA TYPE INTEGER USING (ubicacion::INTEGER);


--C) CREAR CONSTRAINT EN LA TABLA EVENTO DE LA LLAVE FORANEA UBICACION QUE REFERENCIA A CODIGO DE LA TABLA SEDE
ALTER TABLE EVENTO 
ADD CONSTRAINT fk_EVENTO_ubicacion FOREIGN KEY (ubicacion) REFERENCES SEDE (codigo);



