--ISERSIÓN DE DATOS TABLAS REQUERIDAS

--DENTRO DE TABLA 2
INSERT INTO  PAIS VALUES(1,'Guatemala');
INSERT INTO  PAIS VALUES(2,'Francia');
INSERT INTO  PAIS VALUES(3,'Argentina');
INSERT INTO  PAIS VALUES(4,'Alemania');
INSERT INTO  PAIS VALUES(5,'Italia');
INSERT INTO  PAIS VALUES(6,'Brasil');
INSERT INTO  PAIS VALUES(7,'Estados Unidos');

--DENTRO DE TABLA 1
INSERT INTO  PROFESION VALUES(1,'Médico');
INSERT INTO  PROFESION VALUES(2,'Arquitecto');
INSERT INTO  PROFESION VALUES(3,'Ingeniero');
INSERT INTO  PROFESION VALUES(4,'Secretaria');
INSERT INTO  PROFESION VALUES(5,'Auditor');

--DENTRO DE TABLA 5
INSERT INTO  MIEMBRO VALUES(1,'Scott','Mitchell',32,default,'1092 Highland Drive Manitowoc, WI 54220',7,3);
INSERT INTO  MIEMBRO VALUES(2,'Fanette','Poulin',25,25075853,'49, boulevard Aristide Briand 76120 LE GRAND-QUEVILLY',2,4);
INSERT INTO  MIEMBRO VALUES(3,'Laura','Cunha Silva',55,default,'Rua Onze, 86 Uberaba-MG',6,5);
INSERT INTO  MIEMBRO VALUES(4,'Juan José','Lòpez',38,391664921,'26 calle 4-10 zona 11',1,2);
INSERT INTO  MIEMBRO VALUES(5,'Arcangela','Paicucci',39,default,'Via Santa Teresa, 114 90010-Geraci Siculo PA',5,1);
INSERT INTO  MIEMBRO VALUES(6,'Jeuel','Villalpando',31,default,'Acuña de Figeroa 6106 80101 Playa Pascual',3,5);

--DENTRO DE TABLA 9
INSERT INTO  DISCIPLINA VALUES(1,'Atletismo','Saltos de longitud y triples, de altura y con pértiga o garrocha; las pruebas de lanzamiento de martillo, jabalina y disco.');
INSERT INTO  DISCIPLINA VALUES(2,'Bádminton','');
INSERT INTO  DISCIPLINA VALUES(3,'Ciclismo','');
INSERT INTO  DISCIPLINA VALUES(4,'Judo','s un arte marcial que se originó en Japón alrededor de 1880');
INSERT INTO  DISCIPLINA VALUES(5,'Lucha','');
INSERT INTO  DISCIPLINA VALUES(6,'Tenis de Mesa','');
INSERT INTO  DISCIPLINA VALUES(7,'Boxeo','');
INSERT INTO  DISCIPLINA VALUES(8,'Natación','Está presente como deporte en los Juegos desde la primera edición de la era moderna, en Atenas, Grecia, en 1896, donde se disputo en aguas abiertas.');
INSERT INTO  DISCIPLINA VALUES(9,'Esgrima','');
INSERT INTO  DISCIPLINA VALUES(10,'Vela','');


--DENTRO DE TABLA 7
INSERT INTO  TIPO_MEDALLA VALUES(1,'Oro');
INSERT INTO  TIPO_MEDALLA VALUES(2,'Plata');
INSERT INTO  TIPO_MEDALLA VALUES(3,'Broce');
INSERT INTO  TIPO_MEDALLA VALUES(4,'Platino');

--DENTRO DE TABLA 11
INSERT INTO  CATEGORIA VALUES(1,'Clasificatorio');
INSERT INTO  CATEGORIA VALUES(2,'Eliminatorio');
INSERT INTO  CATEGORIA VALUES(3,'Final');

--DENTRO DE TABLA 7
INSERT INTO  TIPO_PARTICIPACION VALUES(1,'Individual');
INSERT INTO  TIPO_PARTICIPACION VALUES(2,'Parejas');
INSERT INTO  TIPO_PARTICIPACION VALUES(3,'Equipos');

--DENTRO DE TABLA 8
INSERT INTO  MEDALLERO VALUES (5,3,1);
INSERT INTO  MEDALLERO VALUES (2,5,1);
INSERT INTO  MEDALLERO VALUES (6,4,3);
INSERT INTO  MEDALLERO VALUES (4,3,4);
INSERT INTO  MEDALLERO VALUES (7,10,3);
INSERT INTO  MEDALLERO VALUES (3,8,2);
INSERT INTO  MEDALLERO VALUES (1,2,1);
INSERT INTO  MEDALLERO VALUES (1,5,4);
INSERT INTO  MEDALLERO VALUES (5,7,2);

--DENTRO DE TABLA 17
INSERT INTO  SEDE VALUES(1,'Gimnasio Metropolitano de Tokio');
INSERT INTO  SEDE VALUES(2,'Jardín del Palacio Imperial de Tokio');
INSERT INTO  SEDE VALUES(3,'Gimnasio Nacional Yoyogi');
INSERT INTO  SEDE VALUES(4,'Nippon Budokan');
INSERT INTO  SEDE VALUES(5,'Estadio Olímpico');

--DENTRO DE TABLA 13
INSERT INTO  EVENTO VALUES(1,3,2,1,1,'2020/7/24 11:00:00');
INSERT INTO  EVENTO VALUES(2,1,6,1,3,'2020/7/26 10:30:00');
INSERT INTO  EVENTO VALUES(3,5,7,1,2,'2020/7/30 18:45:00');
INSERT INTO  EVENTO VALUES(4,2,1,1,1,'2020/8/1 12:15:00');
INSERT INTO  EVENTO VALUES(5,4,10,3,1,'2020/8/8 19:35:00');




