--ELIMIAR COLUMNAS FECHA Y HORA

ALTER TABLE EVENTO 
DROP COLUMN fecha;

ALTER TABLE EVENTO 
DROP COLUMN hora;


--AÑADIR COLUMNA FECHA-HORA QUE PERMITE FECHA Y HORA EN EL MISMO CAMPO
ALTER TABLE EVENTO 
ADD COLUMN fecha_hora TIMESTAMP NOT NULL;



